### ISSUE TITLE
rescaling and recentering data

### ISSUE THREAD

**Issue by nguyentr17** [yuqiliao/InternationalAssessment_MachineLearning#4]
- [x] Find literature on why we need to rescale data before training the model

**Comment by yuqiliao** [comment]
It is good practice to standardize the data before training the model (see [here](https://en.wikipedia.org/wiki/Feature_scaling) and [here](http://www.cs.bilkent.edu.tr/~saksoy/papers/prletters01_likelihood.pdf)).

For the specific case of dealing with 2-level likert scale and 4-level likert scales, we still need to standardize the data (centering and rescaling so that they have a mean of 0 and sd of 1). See [here](https://www.researchgate.net/post/How_can_I_convert_different_point_Likert_scales_for_all_questionnaires_in_a_survey_so_that_they_are_the_same) and [here](http://www-01.ibm.com/support/docview.wss?uid=swg21482329) for a method to standardize the data, which is not exactly the same as haivng a mean of 0 and sd of 1, but the idea is the same.

**Comment by nguyentr17** [comment]
@yuqiliao will add the code to standardize the data.
